# Flux Kustomization for prod cluster
# This file tells Flux what to deploy to the prod cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apptique-prod
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/apptique/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: apptique-examples
  targetNamespace: apptique-prod
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: apptique-prod
